# -*- coding: utf-8 -*-
"""Root-level integrity manifest: CHECKSUM.sha256 and its verifier.

WHY THIS EXISTS
---------------
`guinand-weil-rigorous-numerics-main/CHECKSUM.sha256` pins 116 files, and every
one of its entries names a file *inside that sub-repository*. Nothing in it
reaches the workspace root, and no gate read it, so the 39 root artefacts
(the registers, the reports, the gates themselves) plus `provenance/` and
`harnesses/` had no recorded integrity baseline at all -- F0 residual 4 and
F5 residual F5-R6. This closes both.

SCOPE
-----
    root files          every regular file directly under HERE, except
                        CHECKSUM.sha256 itself (a manifest never hashes itself)
    provenance/         the layered evidence archive, recursively
    harnesses/          the thirteen fault-injection harnesses, recursively

Sub-repositories are deliberately NOT covered: BootLoops-ai/, Dream-RSI-main/,
guinand-weil-rigorous-numerics-main/, hexagon_mhv_symbol_weight_18/, mcp/ and
Theory_of_Everything_Derivations/ are third-party or self-pinned trees. The
Guinand-Weil sub-repo already carries its own manifest; duplicating it here
would create two authorities for one set of bytes.

USAGE
-----
    python checksum_check.py            verify (the suite runs this)
    python checksum_check.py --update   regenerate the manifest

Exit codes: 0 = every listed file matches, 1 = a mismatch, 2 = the manifest is
missing or the scan could not be completed.  2 is never reported as success.
"""
import hashlib
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
MANIFEST_NAME = "CHECKSUM.sha256"
MANIFEST = os.path.join(HERE, MANIFEST_NAME)
TREES = ("provenance", "harnesses")

failures = []


def fail(msg):
    failures.append(msg)
    print("FAIL  %s" % msg)


def check(cond, msg):
    if not cond:
        fail(msg)
    return cond


def sha256_file(path):
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def scan():
    """Relative paths (forward slashes) covered by the manifest, sorted."""
    paths = []
    try:
        entries = sorted(os.listdir(HERE))
    except OSError as exc:
        raise SystemExit("cannot list %s: %s" % (HERE, exc))
    for name in entries:
        full = os.path.join(HERE, name)
        if not os.path.isfile(full):
            continue
        if name == MANIFEST_NAME:
            continue
        if name.lower().endswith(".pyc"):
            continue
        paths.append(name.replace("\\", "/"))
    for tree in TREES:
        base = os.path.join(HERE, tree)
        if not os.path.isdir(base):
            fail("tree %s/ is missing" % tree)
            continue
        for dirpath, dirnames, filenames in os.walk(base):
            dirnames[:] = sorted(d for d in dirnames if d != "__pycache__")
            for fn in sorted(filenames):
                if fn.lower().endswith(".pyc"):
                    continue
                full = os.path.join(dirpath, fn)
                rel = os.path.relpath(full, HERE).replace("\\", "/")
                paths.append(rel)
    return sorted(paths)


def render(paths):
    rows = ["%s" % ("=" * 80),
            "CHECKSUM.sha256 -- SHA-256 of every tracked file at the workspace root,",
            "plus provenance/ and harnesses/.  Generated by checksum_check.py --update.",
            "",
            "Sub-repositories are excluded on purpose: they are third-party or carry",
            "their own manifest (guinand-weil-rigorous-numerics-main/CHECKSUM.sha256,",
            "116 entries, verified separately).",
            ""]
    total = 0
    for rel in paths:
        full = os.path.join(HERE, rel.replace("/", os.sep))
        digest = sha256_file(full)
        size = os.path.getsize(full)
        total += size
        rows.append("SHA-256  %s  %d  %s" % (digest, size, rel))
    rows.append("")
    rows.append("TOTAL FILES : %d" % len(paths))
    rows.append("TOTAL BYTES : %d" % total)
    rows.append("")
    return "\n".join(rows).encode("utf-8")


def update():
    paths = scan()
    if failures:
        return 1
    data = render(paths)
    with open(MANIFEST, "wb") as fh:
        fh.write(data)
    print("ok    manifest written: %s (%d files, %d bytes)"
          % (MANIFEST_NAME, len(paths), len(data)))
    return 0


def verify():
    if not os.path.isfile(MANIFEST):
        print("SKIP  CHECKSUM: %s is absent -- integrity cannot be claimed "
              "without it (run checksum_check.py --update)" % MANIFEST_NAME)
        return 2
    try:
        with open(MANIFEST, "rb") as fh:
            raw = fh.read()
        text = raw.decode("utf-8")
    except (OSError, UnicodeDecodeError) as exc:
        print("SKIP  CHECKSUM: manifest unreadable: %s" % exc)
        return 2

    listed = {}
    for line in text.split("\n"):
        parts = line.split()
        if len(parts) >= 4 and parts[0] == "SHA-256" and len(parts[1]) == 64:
            listed[" ".join(parts[3:])] = (parts[1], int(parts[2]))
    if not listed:
        print("SKIP  CHECKSUM: manifest contains no SHA-256 rows")
        return 2

    current = scan()
    if failures:
        return 1

    matched = 0
    for rel in sorted(listed):
        full = os.path.join(HERE, rel.replace("/", os.sep))
        if not os.path.isfile(full):
            fail("listed but absent: %s" % rel)
            continue
        want_sha, want_len = listed[rel]
        got_len = os.path.getsize(full)
        if got_len != want_len:
            fail("size %d != listed %d: %s" % (got_len, want_len, rel))
            continue
        got_sha = sha256_file(full)
        if got_sha != want_sha:
            fail("sha256 %s != listed %s: %s" % (got_sha[:16], want_sha[:16], rel))
            continue
        matched += 1

    for rel in current:
        if rel not in listed:
            fail("present but not listed: %s" % rel)

    print("%s CHECKSUM  matched %d/%d listed, %d on disk"
          % ("ok  " if not failures else "FAIL  ",
             matched, len(listed), len(current)))
    if failures:
        return 1
    print("CHECKSUM: PASS -- %d files match %s" % (matched, MANIFEST_NAME))
    return 0


def main(argv):
    mode = "update" if "--update" in argv[1:] else "verify"
    if mode == "update":
        return update()
    return verify()


if __name__ == "__main__":
    try:
        sys.exit(main(sys.argv))
    except SystemExit:
        raise
    except Exception as exc:      # a gate must fail, never crash into a traceback
        print("FAIL  CHECKSUM: unexpected error: %s: %s"
              % (type(exc).__name__, exc))
        sys.exit(1)
